# Generated by Django 3.0.3 on 2020-04-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('free_text', models.TextField(verbose_name='Free part')),
                ('pay_text', models.TextField(verbose_name='full part')),
            ],
        ),
    ]
