# Generated by Django 3.0.3 on 2020-04-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pay_text',
            field=models.TextField(verbose_name='Full part'),
        ),
    ]
